# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-17 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_field',
            field=models.CharField(choices=[('design', 'Design'), ('event', 'Event Organizer'), ('teaching', 'Teaching'), ('operations', 'Operations'), ('marketing', 'Marketing'), ('photography', 'Photography'), ('engineering', 'Engineering'), ('media', 'Media and Communication'), ('finance', 'Finance'), ('fashion', 'Fashion'), ('webdev', 'Web Development'), ('other', 'Other')], max_length=140),
        ),
    ]
